# 2D Convolution

## Introduction: 
This notebook demonstrates how to perform a 2D convolution using a filter and data matrix.

## Boundary Handling:
As it is indicated in the figure, when filter slides to the edges of the data matrix, parts of the filter will extend beyond the data matrix. In such cases, we utilize the edge values for padding.

## Procedure:
Compute each element of the result matrix one by one, multiply the filter with the corresponding elements of the data region, then sum the results. Repeat for other positions.

In [5]:
import numpy as np

# Define the filter & data matrix
filter = np.array([[-2, 3, -1],[4, -1, 2],[0, 5, 3]])

data = np.array([[8, 6, -2, 3],[1, 6, 4, 5],[3, 2, -4, 11],[10, -1, 7, 1]])

# Function of 2D convolution
def convolve2d(data, filter):
    data_height, data_width = data.shape
    filter_height, filter_width = filter.shape
    result = np.zeros((data_height, data_width))

    for i in range(data_height):
        for j in range(data_width):
            
            # Extract the region of interest
            region = data[max(i-1, 0):min(i+2, data_height), max(j-1, 0):min(j+2, data_width)]
            
            # Pad the region if necessary
            padded_region = np.pad(region, ((max(1-i, 0), max(i+2-data_height, 0)),
                                           (max(1-j, 0), max(j+2-data_width, 0))), mode='edge')
            
            # Perform the convolution
            result[i, j] = np.sum(padded_region * filter)

    return result

result = convolve2d(data, filter)
print("Result Matrix:")
print(result)

Result Matrix:
[[ 61.  68.  46.  45.]
 [ 38.   8.  22. 119.]
 [ 55.  30.  67.   5.]
 [ 76.  75.   2.  67.]]


### Mapping to the given result matrix, we can get: A = 45, B = 22, C = 55, D = 76.